### PR TITLE
Manually abort transaction in error view

### PR DESCRIPTION
**Pull request by glasserc**
Fixes mozilla-services/kinto-fxa#33.

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Add a changelog entry.
- [ ] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)

r? @Natim 

This fixes mozilla-services/kinto-fxa#33.

This is an ugly hack; the real fix involves fixing kinto#877.

### CODE REVIEW

**Comment by Natim** [comment]
I agree with the fix, I wonder if we can add a test there.

**Comment by leplatrem** [comment]
Good catch!

I think that the transaction is opened by this line: https://github.com/Kinto/kinto/blob/master/kinto/core/authorization.py#L35

Maybe we could put the fix there (something like: if no transaction is opened before the call on the backend, then close it just after there)

**Comment by Natim** [comment]
How do you detect if the transaction is opened or not?

**Comment by leplatrem** [comment]
> How do you detect if the transaction is opened or not?

Maybe with that ? https://github.com/zopefoundation/transaction/blob/master/transaction/_transaction.py#L85

Maybe the current patch is the best way to go after all :)

**Comment by leplatrem** [comment]
After some investigation, we realized that kinto-fxa was not implemented properly. We'll propose a fix there. 

Let's keep #877 and #879 open, it does not hurt to fix them some day, but the root cause is fxa in this case (accessing `request.effective_principals` several times in the request cycle shouldn't induce several hits to auth server and cache backend)

Thanks for spotting the bug !! I close this but remain open to any objection ;)

**Comment by glasserc** [comment]
This was eventually solved in mozilla-services/kinto-fxa#35.

**Pull request closed without merging**
