### PR TITLE
Update overview.rst:  Add Couchbase Mobile

### PR DESCRIPTION
**Pull request by WilliamHoang**
Added in Couchbase Mobile features

### CODE REVIEW

**Comment by almet** [comment]
Hi, thanks for taking the time to add these features to the list on our documentation!

Here are some general remarks:

The tables is malformed and wouldn't render properly. [Here's a diff](https://gist.github.com/0b35d03d945dec341079) you can apply locally to have it working properly.
I tried to read a bit the documentation of couchbase mobile, and it's unclear how are provided some of the features you're marking as "provided":

- Pluggable storage / cache: can you point me where I can configure the storage and caching layers to use some different backend that the default one?
- Fine-grained permissions: same here, I failed to see where fine-grained permissions are provided. Do you have a link to some documentation?

Thanks!

**Comment by WilliamHoang** [comment]
Hey Alexis,

Thanks for the quick reply.  Let me provide some details below..

Pluggable storage:  This is regarding OAuth by third party providers and
also LDAP -
http://blog.couchbase.com/2016/january/how-to-authorize-users-in-sync-gateway
Fine-grain permissions:  This is regarding Channels and Sync-Gateway -
http://blog.couchbase.com/2016/january/using-channels-in-sync-gateway

Let me know if there are additional questions and I will look at the DIFF [
https://gist.github.com/almet/0b35d03d945dec341079 ]

Thanks,
William

William Hoang
*| **Twitter <http://bit.ly/sweetiewill> | LinkedIn
<http://bit.ly/myLinkedIN> | Schedule Event / Calendar
<http://bit.ly/bookwilliam> | *

**Comment by WilliamHoang** [comment]
@almet 

Can add a link too for Couchbase Mobile [ http://developer.couchbase.com/mobile/ ] or I'll open another PR

**Comment by almet** [comment]
By pluggable storage we think more about the database you can use in the backend: postgres, mysql, mongo, etc. Kinto is built around the fact that you can store your data in the backend of your chosing. I believe this is not what Couchbase mobile provides.

**Comment by almet** [comment]
From the article you pasted:

> Channels provide READ access to users between the mobile client and the remote database.

That's not what we call fine-grained permissions. Kinto proposes a matrix of {bucket,collection,record} x {write,read,create} permissions. You can read more about the limitation of CouchDB regarding permissions [on our article](http://www.servicedenuages.fr/en/generic-storage-ecosystem). It seems that these points are also applying to Couchbase mobile. I might be wrong here, so don't hesitate to provide some more information about how ACLs are handled so we can update our documentation properly.

**Comment by almet** [comment]
Hey @WilliamHoang . I've read [your article](http://blog.couchbase.com/2016/january/migration-from-parse-to-couchbase) with interest, and I've seen that you've indicated there that couchbase is doing pluggable storage and cache. How couchbase is doing pluggable storage is still unclear to me.

Also, it seems you reused the comparison table from here without giving credit. Beware that the content in this repository is [released under the Apache license](https://github.com/Kinto/kinto/blob/master/LICENSE) and as such it's better to cite the original authors if possible.

Thanks!

**Comment by almet** [comment]
@WilliamHoang Did you find the time to fix the issues I raised here? Otherwise I'll close it for now, and you can open another pull request with the correct explanation. Thanks.

**Comment by WilliamHoang** [comment]
Hey Alexis,

Let me try to get to this ASAP today!

Thanks,
William

William Hoang
*| **Twitter <http://bit.ly/sweetiewill> | LinkedIn
<http://bit.ly/myLinkedIN> | Schedule Event / Calendar
<http://bit.ly/bookwilliam> | *

**Comment by almet** [comment]
No news, I'll close this pull request for now. Feel free to re-open if needed.

**Comment by WilliamHoang** [comment]
Hey Alexis,

I will make a new one.  Sorry I am dealing with family event and been MIA
for the pass 1-2 weeks.

Thanks,
William

William Hoang
*| **Twitter <http://bit.ly/sweetiewill> | LinkedIn
<http://bit.ly/myLinkedIN> | Schedule Event / Calendar
<http://bit.ly/bookwilliam> | *

**Pull request closed without merging**
