### PR TITLE
Fix status of 403 Forbidden in docs

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by gabisurita** [comment]
I remember fixing this. https://github.com/Kinto/kinto/commit/c6a8606c6bee58c29246c7e0a63ae89cb028fedd

I guess it's right on the current master.

**Comment by leplatrem** [comment]
https://twitter.com/ThePracticalDev/status/833770687940669441

**Comment by Natim** [comment]
> I guess it's right on the current master.

Then I don't understand this diff...

**Comment by gabisurita** [comment]
>Then I don't understand this diff... 

I want to merge it just to see what happens...

**Comment by Natim** [comment]
> but I want to merge it just to see what happens...

Same here :D

**Comment by Natim** [comment]
Well here is what happenned: https://github.com/Kinto/kinto/commit/71209e2daedac0f6a071230e234841ac085ff725

An empty merge commit \o/

**Pull request merged**
