### PR TITLE
Remove dead code (ref #53)

### PR DESCRIPTION
**Pull request by leplatrem**
@ametaireau @Natim  r?

### CODE REVIEW

**Comment by Natim** [comment]
Looks good to me, I fixed the one flake8 error waiting on travis.

**Comment by Natim** [comment]
But I am wondering if this is dead code or missing tests?

**Comment by Natim** [comment]
I did some manual checking and nothing wrong seems happen.

**Comment by leplatrem** [comment]
There might be some corner cases where this code was useful. But since the tests pass without it, it is dead code :)
If we figure out what were the corner cases, we'll add a test and restore it...

**Comment by ametaireau** [comment]
yes, its the best strategy :-)

**Pull request merged**
