### PR TITLE
Preparing release 6.0.0

### PR DESCRIPTION
**Pull request by leplatrem**
- [x] Wait for #1095

### CODE REVIEW

**Comment by gabisurita** [comment]
Should we wait for #1095?

**Comment by leplatrem** [comment]
> Should we wait for #1095?

It was marked as WIP so I didn't bother... What do you think?

**Comment by gabisurita** [comment]
I think we should probably fix the make serve recipe before releasing. I know it's more important for development but I think it's bad to make a release without it working.

**Comment by Natim** [comment]
The thing is even with #1095 fixed, the --reload option won't work until https://github.com/Pylons/pyramid/pull/2962 is fixed.

**Comment by Natim** [comment]
In the meantime we can remove --reload from the ``make serve``

**Pull request merged**
