### PR TITLE
Fix docs warning

### PR DESCRIPTION
**Pull request by sunakshi96**
Fixes #

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Add a changelog entry.
- [ ] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)

r? @

### CODE REVIEW

**Comment by sunakshi96** [comment]
Hii
Oh the changes are made to fix the warning caused by a python class :'Sequence'. May I please know which package are we referring here?

**Comment by gabisurita** [comment]
Sorry, package refers to this repository. 

I've couldn't reproduce the warning here. Can you paste your log? Where is Sequence referred in the documentation?

**Comment by sunakshi96** [comment]
`
sunakshi@sunakshi-Inspiron-3542:~/kinto$ make docs
.venv/bin/sphinx-build -a -W -n -b html -d docs/_build/doctrees docs docs/_build/html
Running Sphinx v1.5.2
loading pickled environment... done
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] tutorials/write-plugin                                                                                 

Warning, treated as error:
/home/sunakshi/kinto/docs/core/resource.rst:159: WARNING: py:class reference target not found: Sequence

Makefile:132: recipe for target 'docs' failed
make: *** [docs] Error 1
`

**Comment by sunakshi96** [comment]
Hey
The Sequence is not mentioned in the documentation. Since the warning mentions the target Sequence is not found so I simply added the ('py:class','Sequence') under nitpick_ignore in conf.py file in /kinto/docs/core folder.

**Comment by gabisurita** [comment]
I've got it. It was included by the reference to `kinto.core.resource.schema`. Nice catch! :) 

What about the rest of the changes? Are they needed? I see that there are some indentation problems on some lines too.

**Comment by sunakshi96** [comment]
Hey
Actually I copied the rest of the changes from the #961. Okay I ll fix the indentation. May I know how to reference the new commit on this PR?

**Comment by gabisurita** [comment]
Actually I copied the rest of the changes from the #961. Okay I ll fix the indentation. May I know how to reference the new commit on this PR?

> You already did it. You just need to push it to your branch. :)

Type is still commented. Can you fix that too? Also you may add your name to the contributors file.

**Comment by sunakshi96** [comment]
> Type is still commented. Can you fix that too?

Yes I can!

**Comment by sunakshi96** [comment]
Thank you @gabisurita

**Comment by gabisurita** [comment]
Thank you @sunakshi96! Is you name already on the `CONTRIBUTORS.rst` file? If not, can you add it please?

**Pull request merged**
