### PR TITLE
Prepare 2.1.0

### PR DESCRIPTION
**Pull request by leplatrem**
**Step 1**
```
$ git co -b prepare-X.X
$ prerelease
$ vim docs/conf.py
$ git ci -a --amend
$ git push origin prepare-X.X
```

* [x] Merge remaining pull requests
* [x] Update changelog
* [x] Update version in docs/conf.py
* [x] Version dependencies
* [x] If cliquet was updated, update the link to default settings in the docs
* [x] if cliquet protocol was updated, upgrade API protocol in docs/

**Step 2**
```
$ git co master
$ git merge --no-ff prepare-X.X
$ release
$ postrelease
```
* [ ] Tag vX.Y.Z
* [ ] Publish on Pypi

**Step 3**
* [ ] Close milestone in Github
* [ ] Add entry in Github release page
* [ ] Create next milestone in Github
* [ ] Configure the version in ReadTheDocs
* [ ] Update kinto version in kinto.js repo
* [ ] Send mail to ML
* [ ] Tweet!

### CODE REVIEW

**Comment by leplatrem** [comment]
@almet r?

**Comment by Natim** [comment]
r+

**Comment by Natim** [comment]
r+

**Comment by almet** [comment]
Great, thanks for the work :)

**Pull request merged**
