### PR TITLE
Start on type annotations

### PR DESCRIPTION
**Pull request by Cnidarias**
So this is a start on adding type annotations

I wanted to get some feedback before I continue on this - I just used monkeytype to generate the annotations - this does yield pretty good results but with some of these functions the function definitions is _very long_  

Should we just continue on this road? Any other options/improvements because this isn't really pretty.
(it will also fail flake8 right now)

I guess one option would be to let something like black run over the code afterwards to get some decent formatting but I am quite unsure.

So some feedback would be great!

### CODE REVIEW

**Comment by leplatrem** [comment]
Thanks for starting this :) 

@Natim would be happy if we would enable Black here ;) 

I have one feedback: I don't think having that kind of annotations are helpful: `List[Dict[str, Union[int, str]]]:`. If we could have something like `List[StoredObject]` and somewhere have `StoredObject` defined to be a dict with at least an id, last_modified...
Is it possible?

**Comment by Cnidarias** [comment]
Sure,

yes this is very possible. I know some larger projects basically have a type def file where they define such horrible types to shorten them.

I will let black run over it and refactor some of the larger type annotations tonight when I get home from work, then we can see if the direction we are heading is any good or not

**Comment by Natim** [comment]
In the meantime black work has been merged.

**Comment by leplatrem** [comment]
@Cnidarias should we keep this PR open? 
Now that we have black, and that the core is a bit more polished (#1827  #1932), we could get back to this :)

**Comment by leplatrem** [comment]
I'll take this as a «no» :) 

Thanks for starting this, don't hesitate to shout out if you'd like to come back to this!

**Pull request closed without merging**
