### PR TITLE
Update depreciated warn method

### LINKED ISSUE #1903: Remove deprecation: The 'warn' method is deprecated, use 'warning' instead
```
/home/mathieu/Code/Mozilla/kinto/kinto/core/authorization.py:107: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    extra=dict(userid=principals[0], uri=object_id, perm=permission),
  /home/mathieu/Code/Mozilla/kinto/kinto/core/authorization.py:107: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    extra=dict(userid=principals[0], uri=object_id, perm=permission),

```

### PR DESCRIPTION
**Pull request by peterr101**
Fixes #1903 

- [x] Add a changelog entry.
- [x] Add your name in the contributors file.

### CODE REVIEW

**Comment by peterr101** [comment]
Is there any need here to update the CHANGELOG?

**Comment by Natim** [comment]
> Is there any need here to update the CHANGELOG?

Yes please

**Comment by peterr101** [comment]
Okay the changelog has been updated and the fix seems to pass all the tests.

**Comment by Natim** [comment]
Thanks @peterr101

**Pull request merged**
