### PR TITLE
Move default values to dedicated column in docs (fixes #255)

### LINKED ISSUE #255: Add column for default values in settings documentation
We should add the default values in the config doc. e.g.: what's the default size of the pool?

### PR DESCRIPTION
**Pull request by leplatrem**
@almet r?

### CODE REVIEW

**Comment by Natim** [comment]
Yes much better :+1:

**Comment by almet** [comment]
Thanks for doing this. I'm actually not sure about the results, when looking at them.

small

In this example, the table is almost unreadable...

**Comment by almet** [comment]
Also, I wonder if the default value should come at the end (after the explanation and not before) ?

**Comment by leplatrem** [comment]
That's not so complicated with modern editors...
screencast_17-12-2015_10 08 26

But I think I prefer the default next to the setting name.

I will try to do something in CSS to set a max-width on the second column

**Comment by almet** [comment]
Cool :)

**Comment by leplatrem** [comment]
capture d ecran de 2015-12-17 16-17-45

**Pull request merged**
