### PR TITLE
[WIP] Add a debian folder for packaging

### PR DESCRIPTION
**Pull request by almet**
This is my very first debian package built for python. It probably isn't the greatest, but well, that's at least a start.

- [x] Create a minimalist debian folder, with the required files;
- [ ] Make it run the tests;
- [ ] Expose the `kinto` command to run the server

To test it: run `dpkg-buildpackage -us -uc`.

### CODE REVIEW

**Comment by almet** [comment]
Currently, I've added a `--no-test` option in `debian/rules` because it fails with an error:

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    dependency_links=DEPENDENCY_LINKS)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/alexis/dev/kinto/debian/kinto-server/usr/share/python/kinto-server/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/alexis/dev/kinto/debian/kinto-server/usr/share/python/kinto-server/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/home/alexis/dev/kinto/debian/kinto-server/usr/share/python/kinto-server/local/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/alexis/dev/kinto/debian/kinto-server/usr/share/python/kinto-server/local/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_views_flush'
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 92, in main
    deploy.run_tests()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 156, in run_tests
    subprocess.check_call([python, 'setup.py', 'test'], cwd=self.sourcedirectory)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by almet** [comment]
Might be interesting: https://github.com/nylas/sync-engine/commit/bb4881d876d9a99c42a07ac3d97336c15cc83ee3

**Comment by leplatrem** [comment]
I would be in favor of moving this to the `kinto-dist` repo

**Comment by tarekziade** [comment]
Yeah let's move it to kinto-dist - https://github.com/mozilla-services/kinto-dist/issues/45

Thanks

**Pull request closed without merging**
