### PR TITLE
fix 404 status code on patch and delete object

### PR DESCRIPTION
**Pull request by gabisurita**
Another tiny fix on the docs status codes.

### CODE REVIEW

**Comment by glasserc** [comment]
I'm not sure about this one -- I think the docs are correct. If you try to delete a bucket that doesn't exist, you get a 403. I think this is so that we don't leak information about things that are there but can't be seen because you don't have permission.

```
> http PUT localhost:8888/v1/buckets/abcd -a 'user:pass2'
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 155
Content-Type: application/json; charset=UTF-8
Date: Fri, 11 Nov 2016 22:26:32 GMT
Etag: "1478903192992"
Last-Modified: Fri, 11 Nov 2016 22:26:32 GMT
Server: waitress

{
    "data": {
        "id": "abcd",
        "last_modified": 1478903192992
    },
    "permissions": {
        "write": [
            "basicauth:db446a4e0ffd571c291d2d7e20bfd978a1e92cd5fe566ca796af74c40943c583"
        ]
    }
}

> http DELETE localhost:8888/v1/buckets/abcd -a 'user:pass2'
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 67
Content-Type: application/json; charset=UTF-8
Date: Fri, 11 Nov 2016 22:26:35 GMT
Server: waitress

{
    "data": {
        "deleted": true,
        "id": "abcd",
        "last_modified": 1478903195786
    }
}

> http DELETE localhost:8888/v1/buckets/abcd -a 'user:pass2'
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Fri, 11 Nov 2016 22:26:36 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}
```

**Comment by gabisurita** [comment]
That's is indeed true for buckets (I'm sorry, at first glance I didn't got that), but not for collections and records on an existing bucket.

Some examples:

**DELETE on non-existing bucket**
```
[gabi@nasa ~]$ http DELETE localhost:8888/v1/buckets/blah --auth aaa:aaa
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:48:29 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}
```

**DELETE on a collection inside a non-existing bucket**
```
$ http DELETE localhost:8888/v1/buckets/blah/collections/bleh --auth aaa:aaa
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:48:50 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}
```

**DELETE on a non-existing collection inside an existing bucket**
```
$ http DELETE localhost:8888/v1/buckets/bbb/collections/c --auth aaa:aaa
HTTP/1.1 404 Not Found
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 94
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:51:17 GMT
Server: waitress

{
    "code": 404,
    "details": {
        "id": "c",
        "resource_name": "collection"
    },
    "errno": 110,
    "error": "Not Found"
}
```


Also, I've mentioned `DELETE` first, but the same applies for `PATCH`.


**PATCH on non-existing bucket**
```
[gabi@nasa ~]$ http PATCH localhost:8888/v1/buckets/blah --auth aaa:aaa
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:54:16 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}
```

**PATCH on a collection inside a non-existing bucket**
```
[gabi@nasa ~]$ http PATCH localhost:8888/v1/buckets/blah/collections/bleh --auth aaa:aaa
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:54:27 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}
```

**PATCH on a non-existing collection inside an existing bucket**
```
[gabi@nasa ~]$ http PATCH localhost:8888/v1/buckets/bbb/collections/c --auth aaa:aaa
HTTP/1.1 404 Not Found
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 94
Content-Type: application/json; charset=UTF-8
Date: Sat, 12 Nov 2016 00:54:35 GMT
Server: waitress

{
    "code": 404,
    "details": {
        "id": "c",
        "resource_name": "collection"
    },
    "errno": 110,
    "error": "Not Found"
}
```

**Comment by gabisurita** [comment]
I'm not sure this is expected in the permissions scope, but if it is, I think we should document the different behaviour for `bucket`, `collection` and `record` objects separately (which means splitting the `_status*.rst` files). What do you think?

**Comment by glasserc** [comment]
That's super weird. Maybe @leplatrem or @Natim knows whether these should be consistent or if it's meant to be like this? If it's meant to be like this, I agree we should document it.

**Comment by Natim** [comment]
It is meant to be like this. If it doesn't exists but you don't have the permission to know it you will have a 403. However if you have the permission to know it you will get a 404.

**Comment by Natim** [comment]
However it is not specific to buckets, if you give permission to anyone to read bucket you will get a 404 as well. Or if you don't have the permission to read the collection or record you will get a 403.

**Comment by gabisurita** [comment]
@Natim, got it! So i think that clarifies a bit the behaviour for `delete` and `patch`. What do you think?

**Comment by gabisurita** [comment]
One more thing, the user is expected to have `write` permissions on the parent to get a `404` instead of `403`?

```
$ echo '{"permissions": {"read": ["system.Everyone"] }}' | http PUT localhost:8888/v1/buckets/b1 -a aaa:aaa
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 221
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Nov 2016 18:22:19 GMT
Etag: "1479147739801"
Last-Modified: Mon, 14 Nov 2016 18:22:19 GMT
Server: waitress

{
    "data": {
        "id": "b1",
        "last_modified": 1479147739801
    },
    "permissions": {
        "collection:create": [],
        "group:create": [],
        "read": [
            "system.Everyone"
        ],
        "write": [
            "basicauth:e786965bf09bdbdff1c9dcb892354d6200439ae98c045515225740ff7709ebef"
        ]
    }
}

$ http PATCH localhost:8888/v1/buckets/b1/collections/c2 -a aaa:aaa
HTTP/1.1 404 Not Found
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Nov 2016 18:22:37 GMT
Server: waitress

{
    "code": 404,
    "details": {
        "id": "c2",
        "resource_name": "collection"
    },
    "errno": 110,
    "error": "Not Found"
}

$ http PATCH localhost:8888/v1/buckets/b1/collections/c2 -a bbb:bbb
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Nov 2016 18:22:49 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}

$ http DELETE localhost:8888/v1/buckets/b1/collections/c2 -a aaa:aaa
HTTP/1.1 404 Not Found
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Nov 2016 18:23:10 GMT
Server: waitress

{
    "code": 404,
    "details": {
        "id": "c2",
        "resource_name": "collection"
    },
    "errno": 110,
    "error": "Not Found"
}

$ http DELETE localhost:8888/v1/buckets/b1/collections/c2 -a bbb:bbb
HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Nov 2016 18:23:19 GMT
Server: waitress

{
    "code": 403,
    "errno": 121,
    "error": "Forbidden",
    "message": "This user cannot access this resource."
}

```

**Comment by glasserc** [comment]
The build failure is unrelated to these changes -- a fix exists in https://github.com/Kinto/kinto/pull/916, although I'm not sure what its status is.

I feel like listing so many possible reasons for a 403 is a little overwhelming. I'd rather see a more "global" note about Forbidden errors explaining that we sometimes return them instead of 404s if the user doesn't have access to the place where an object would be.

**Comment by Natim** [comment]
Yes I guess the read permission on the parent should be enough to have a 404.

**Comment by gabisurita** [comment]
> Yes I guess the read permission on the parent should be enough to have a 404.

Should we open an issue for that? Right now `write` is required... (as on the example above).

**Comment by Natim** [comment]
Yes we should.

**Pull request merged**
