### PR TITLE
Remove JSON Patch type from viewset

### PR DESCRIPTION
**Pull request by gabisurita**
We use a separate view for handling JSON Patch, so it doesn't make much sense to keep it on the accepted types for the regular JSON view.

r? @leplatrem

### CODE REVIEW

**Comment by gabisurita** [comment]
> It may deserve a mention as an internal change?

I didn't think it was necessary, but when it comes logging more is usually better than less. :P

**Comment by gabisurita** [comment]
The load test are failing, but I guess  this is probably not related to this change. Do you have any idea why?

**Comment by leplatrem** [comment]
> Do you have any idea why?

It seems related to requests. There was a release 3 hours ago, we can try to downgrade it maybe?

```
    AttributeError: 'module' object has no attribute 'epoll'    Traceback: 

  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329, in run

    testMethod()

  File "loadtest/tutorial.py", line 21, in test_tutorial

    self.play_user_default_bucket_tutorial()

  File "loadtest/tutorial.py", line 27, in play_user_default_bucket_tutorial

    collection_url = self.collection_url('default', collection_id)

  File "loadtest/__init__.py", line 85, in collection_url

    headers={'If-None-Match': '*'})

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 546, in put

    return self.request('PUT', url, data=data, **kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/loads/measure.py", line 82, in request

    method, url, headers=headers, **kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 488, in request

    resp = self.send(prep, **send_kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/loads/measure.py", line 90, in send

    res = _Session.send(self, request, **kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 609, in send

    r = adapter.send(request, **kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 423, in send

    timeout=timeout

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen

    conn = self._get_conn(timeout=pool_timeout)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 241, in _get_conn

    if conn and is_connection_dropped(conn):

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 27, in is_connection_dropped

    return bool(wait_for_read(sock, timeout=0.0))

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/util/wait.py", line 33, in wait_for_read

    return _wait_for_io_events(socks, EVENT_READ, timeout)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/util/wait.py", line 22, in _wait_for_io_events

    with DefaultSelector() as selector:

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/util/selectors.py", line 364, in __init__

    self._epoll = select.epoll()

1 occurrences of: 

    AttributeError: 'module' object has no attribute 'epoll'    Traceback: 

  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329, in run

    testMethod()
```

**Comment by gabisurita** [comment]
Downgrading fixed loadtests but now `pypy` is failing. 😞

**Comment by glasserc** [comment]
I don't know what changed that made this test start to fail, but I don't understand why it should have ever worked, and why it doesn't fail in the other non-pypy builds. It's failing because it's trying to get a `current_resource_name` from a mock to use as details in an HTTP error. `current_resource_name` produces another mock, which means that the details can't be serialized. I think you can work around it by setting a `current_resource_name` in the mock (in `get_request()`).

**Pull request merged**
