### PR TITLE
[WIP] Add the preliminary code for working on mongodb data storage

### PR DESCRIPTION
**Pull request by Lothiraldan**
Still WIP but should be sufficient to work on with @Natim

### CODE REVIEW

**Comment by Natim** [comment]
Thank you for putting this here.

**Comment by leplatrem** [comment]
Hey guyz! Cool to see you here ;)

Before you start implementing the bodies of this scaffold, can you detail a bit the value added by this new backend?

For example, I remember a while ago that AlwaysData was stuck with an old Postgresql version, and Mongo was mentioned.

Since it will add some setup/integration «*overhead*» we can list pros/cons and see if it is relevant to put it in the core or as a community-plugin!

Thanks for starting this!

**Comment by Natim** [comment]
The plan is to make it so that we can deploy Kinto in AlwaysData.
The plan is also to makes it a community backend. We started working on this here to make the setup easier (plugin tests and stuff) but we will extract it at some point.

As you may have seen this is just WIP PR so that we don't loose the work that have been done so far nothing more.

**Comment by tarekziade** [comment]
Very nice ! 

Maybe we could have this new backend implemented in its own repository ? e.g. kinto-mongodb. 

Keeping kinto as small as possible is making it easier to deploy when you don't use mongodb - and gives us a less complex requirements handling. For instance, no need to add a bunch of Skips in the tests.

**Comment by tarekziade** [comment]
Closing this, feel free to add a link to a repo in case you start back this work. Thanks

**Pull request closed without merging**
