### PR TITLE
Next-Page with filtering on a not mandatory field raises a KeyError.

### PR DESCRIPTION
**Pull request by Natim**
Reproductible easily with the Kinto-Admin. Let me write a test for it.

### CODE REVIEW

**Comment by Natim** [comment]
@leplatrem I would like to talk a bit with you to make sure we are adopting the correct strategy here.

**Comment by n1k0** [comment]
LGTM :)

**Comment by leplatrem** [comment]
The fix looks good in apparence indeed. I'm ok to merge.

We could go further and try to setup a test where this would have an impact. For example, make sure that no record is skipped not duplicated when going through pagination when the last record of a page has not the field used in the filter or sort...

**Comment by Natim** [comment]
your intuition was correct...

**Comment by leplatrem** [comment]
What's the status of this now that #1116 was merged?

**Comment by Natim** [comment]
Let me add the tests in a new PR so that we can see if we still have the issue.

**Comment by Natim** [comment]
Superseeded by #1253

**Pull request closed without merging**
