### PR TITLE
Document #858

### PR DESCRIPTION
**Pull request by sunakshi96**
Fixes #

- [x] Add documentation.
- [x] Add tests.
- [x] Add a changelog entry.
- [x] Add your name in the contributors file.
- [x] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)

### CODE REVIEW

**Comment by Natim** [comment]
Could you please update your PR branch, it is easier to follow up on the previous pull-request.

**Comment by Natim** [comment]
This one: https://github.com/Kinto/kinto/pull/864

**Comment by sunakshi96** [comment]
Okay I will do that

**Comment by Natim** [comment]
Thanks

**Pull request closed without merging**
