### PR TITLE
pyramid-mailer dependency is missing from requirements

### PR DESCRIPTION
**Pull request by glasserc**

### CODE REVIEW

**Comment by glasserc** [comment]
The tests failed... I guess that proves my point, but not in the way I expected.

**Comment by Natim** [comment]
I guess it isn't enough to put it in requirements.txt we should probably also add it in setup.py.

**Comment by glasserc** [comment]
It looks like it was added in https://github.com/Kinto/kinto/pull/1982.

**Comment by Natim** [comment]
I see what you mean.

**Pull request merged**
