### PR TITLE
Added the changes capability.

### PR DESCRIPTION
**Pull request by Sayli-Karnik**

### CODE REVIEW

**Comment by Natim** [comment]
You are not supposed to have all this build files.

**Comment by Sayli-Karnik** [comment]
Oh right, I'll make the changes!

**Comment by leplatrem** [comment]
@Sayli-Karnik, if you want to implement this issue: https://github.com/Kinto/kinto-changes/issues/6, you should contribute it to the repository there!

It is generally a good practice to keep repositories uncoupled and independant :)

Your changes are mostly valid, it's just they belong there ;)

**Comment by Natim** [comment]
@Sayli-Karnik I am closing this PR here and I would be in IRC to help you if you need it to do what @leplatrem said.

**Pull request closed without merging**
