### PR TITLE
Add a docker ignore file.

### PR DESCRIPTION
**Pull request by Natim**
r? @leplatrem

### CODE REVIEW

**Comment by leplatrem** [comment]
the `ADD` commands can now be simplified then

**Comment by almet** [comment]
Ah, that's cool, didn't know about it :-)

**Comment by Natim** [comment]
The image seems 20MB bigger but I don't understand why :)

**Comment by Natim** [comment]
```
16K	CHANGELOG.rst
4.0K	CONTRIBUTORS.rst
4.0K	Dockerfile
4.0K	LICENSE
4.0K	MANIFEST.in
4.0K	Makefile
4.0K	README.rst
4.0K	app.wsgi
4.0K	dev-requirements.txt
4.0K	docker-compose.yml
20K	examples
288K	kinto
52K	kinto.egg-info
0	kinto.log
4.0K	requirements.txt
4.0K	setup.cfg
4.0K	setup.py
4.0K	tox.ini
```

**Comment by Natim** [comment]
But I think it is because we've added some plugins as well we should be good.

**Comment by leplatrem** [comment]
r+

**Pull request merged**
