### PR TITLE
instructions to run a local kinto{PostgreSQL 9.4+}

### PR DESCRIPTION
**Pull request by essymo**
Fixes #

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Add a changelog entry.
- [ ] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)

r? @

### CODE REVIEW

**Comment by essymo** [comment]
Added some instruction on how to install postgresql 9.4+

**Comment by glasserc** [comment]
This is meant to address #788. r? @leplatrem

**Comment by leplatrem** [comment]
I'm very sorry to say that, but unfortunatly nope, that was not the idea of #788 :((

From what I can see, this PR copies the wiki page to the *Running in production* docs. I'd like to keep the Kinto focused on what is specific to Kinto+postgresql, so that users which are familiar with PostgreSQL do not miss any crucial information. Users that are not familiar should first get their server running (*possibly with external/up-to-date/official docs*) and then come back to Kinto.

I added some details in #788 

Sorry about the time lost here :(

**Comment by leplatrem** [comment]
I'm closing in favor of #839 :(

**Pull request closed without merging**
