### PR TITLE
Fixed showing of backend type twice in StatsD backend keys

### LINKED ISSUE #857: StatsD backend keys contain twice backend type
capture d ecran de 2016-10-10 10-26-46

`kinto.storage.storage.get` instead of `kinto.storage.get` or `kinto.storage.call.get`

### PR DESCRIPTION
**Pull request by d1ndra**
Fixes #857 

r? @leplatrem

### CODE REVIEW

**Comment by leplatrem** [comment]
Oh sorry, I forgot to mention: you should update the CHANGELOG too

**Comment by Natim** [comment]
And add your name in contributors if it is not already the case.

**Comment by d1ndra** [comment]
@leplatrem Made requested changes.

**Comment by leplatrem** [comment]
Thanks!

**Pull request merged**
