### PR TITLE
Remove the link to Twitter, it's almost useless.

### PR DESCRIPTION
**Pull request by almet**

### CODE REVIEW

**Comment by Natim** [comment]
I think it good to tell people to use the #kinto hashtag when they want to speak about it, isn't it?

**Comment by almet** [comment]
Well in practice it's useless to me, since I can't subscribe to it.

**Comment by Natim** [comment]
Then it might be wise to create a kinto-storage account?

**Comment by Natim** [comment]
With some Twitter clients you can :)

**Pull request closed without merging**
