### PR TITLE
Update to Pyramid 1.8

### LINKED ISSUE #1008: Port Kinto for Pyramid 1.8
Pyramid 1.8 is breaking a number of things:

- BasicAuth authn policy
- pserve http_port config.

Right now it is still an alpha release but it gets installed on time to time.

### PR DESCRIPTION
**Pull request by birdbrained**
Pyramid moved this out of the class and into its own function.

Fixes #1008

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Add a changelog entry.
- [ ] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)

r? @

### CODE REVIEW

**Comment by glasserc** [comment]
Hi! Thanks for the contribution! Sorry nobody has had time to look at this. The change looks OK by itself but the tests are failing, I think because we have a constraint that forces pyramid 1.7. Could you please update that too?

**Comment by Natim** [comment]
Apparently there are still 2 tests not passing anymore: https://travis-ci.org/Kinto/kinto/jobs/189584939

**Comment by leplatrem** [comment]
Tests fail because Pyramid 1.7 is used. @birdbrained could you rebase/update the pull-request please?

**Comment by Natim** [comment]
Thanks @birdbrained for starting this. I am taking over in #1087

**Pull request closed without merging**
