### PR TITLE
Prepare 3.3.0

### PR DESCRIPTION
**Pull request by leplatrem**
**Step 1**

* [x] Merge remaining pull requests
* [x] Update changelog
* [x] Update version in docs/conf.py
* [x] Version dependencies
* [x] If the protocol was updated, upgrade API protocol in `docs/api/index.rst` and mention the new protocol version in `CHANGELOG.rst`
* [x] Update release date in `docs/api/index.rst`

**Step 2**

* [ ] Tag vX.Y.Z
* [ ] Publish on Pypi

**Step 3**
* [ ] Close milestone in Github
* [ ] Add entry in Github release page
* [ ] Create next milestone in Github
* [ ] Configure the version in ReadTheDocs
* [ ] Check that a Docker image was built
* [ ] Send mail to ML
* [ ] Tweet!

- [ ] Deploy new version on demo server
- [ ] Upgrade dependency in ``kinto-dist`` repo
- [ ] Upgrade version targetted in ``kinto-heroku`` repo
- [ ] Upgrade version of Kinto server for the tests of clients and plugins repos
  (*kinto-http.js, kinto-http.py, kinto-attachment, etc.*)

@Natim  r?

### CODE REVIEW

**Comment by Natim** [comment]
Shall we rebase?

**Comment by leplatrem** [comment]
@Natim I just rebased.

**Comment by Natim** [comment]
r+

**Comment by leplatrem** [comment]
capture d ecran de 2016-07-18 12-53-45

**Comment by Natim** [comment]
:)

**Pull request merged**
