### PR TITLE
Group permissions are not working

### PR DESCRIPTION
**Pull request by aegaas**
Team,

I'm fairly new to python development, but I wanted to build a project on kinto that uses group permissions. Here you see a test that expresses what I'm seeing in the real world, that when I setup a group write permissions on a record, the user that should be able to read and write to it cannot and he gets a 403 instead.

I understand that this functionality might depend on cliquet in order to get fixed, but I wanted to surface this to the team to see if its a known issue or maybe I was doing something wrong.

### CODE REVIEW

**Comment by leplatrem** [comment]
Thank you for this report!

This is very (very) pleasant to receive a test case as a bug report!

From what I see it looks like you're using the username instead of the user id in the group definition.

The user id can be obtained from the root URL when authenticated.

We'll double check all this tomorrow but the documentation probably deserves a good clarification on this!

**Comment by aegaas** [comment]
@leplatrem thanks for getting back to me so quickly! I think maybe I incorrectly assumed that the create_group call would figure out the hashes for me. We have a suite of rspec tests that use these basicauth:<hash> keys in groups and the same behavior occurs. 

If I instead use the keys directly in the permissions hash, everything works alright, but that would quickly become unmanageable with a large dataset. I'd very much prefer to use 'group:<name>' definition in record and collection permission objects.

**Comment by leplatrem** [comment]
Excellent, thank you! I I will spend some time on it, that indeed look very much like a bug!

**Comment by Natim** [comment]
It is because ``group:brewers`` is not the right way to name a group in a permissions.

If you use ``/buckets/beers/groups/brewers`` instead it should work just fine.

**Comment by Natim** [comment]
I couldn't add my commit there so I added it here #388 
Nevertheless I would like to thank you for opening this PR with a test it is really useful for us and it definitely means we need to improve the documentation around that.

**Comment by almet** [comment]
Thanks for the report and the test case :-)

This should make the documentation easier to read: https://github.com/Kinto/kinto/pull/389 (credits to @natim). Don't hesitate to add some feedback there.

**Comment by aegaas** [comment]
Thank you everyone for jumping on this in record time! The test passes, but unfortunately I have a larger test suite that doesn't seem to be taking the changes as well as I hoped. Its likely I need to figure out how to update kinto on my AWS instance to prove this out.

I'll take some time today to prove this out and perhaps add more test cases to fit what I'm seeing in the real world.

**Comment by Natim** [comment]
@aegaas note that we should probably release a version of Kinto quite soon. (Last one is more than a month old now.)

**Comment by aegaas** [comment]
I have added a more complex test case that uses 2 users, aaron and kelly. aaron writes a record to a collection and kelly is able to read it!

**Comment by Natim** [comment]
@aegaas Your new test is passing right?

**Comment by Natim** [comment]
@aegaas You should probably create new branch for further investigations.

If you want to rebase on #388 you can use:

    git checkout Kinto/master -b kinto_master
    git pull Kinto master
    git checkout -b investigating_permissions
    git cherry-pick 62ca813
    git push aegaas investigating_permissions -u

I will close this PR for now since the original problem has been merged.

**Comment by aegaas** [comment]
Thanks @Natim this was very helpful. I have updated my local build and will investigate further.

**Comment by aegaas** [comment]
Team,

While the test suite is showing all green, which is great, I've been validating against a real kinto instance which is not showing the same results:

the gist linked is showing my debug output where I have a system account, create a group, and then create a collection with write permissions. I then attempt to write to the collection but get a 403. What am I doing wrong?

https://gist.github.com/aegaas/c7c145d39fcade50e3ad

**Comment by Natim** [comment]
@aegaas Can you join #kinto on IRC I have some questions for you regarding what you are trying to do.

**Comment by Natim** [comment]
@aegaas I tried to create a working scenario, not sure if it is what you are trying to do though, hope this helps:

Install HTTPie before running the bash script. (```sudo pip install httpie``)

```
#!/bin/bash -v

AARONEGAAS_USER_ID="basicauth:fdef7420df4f59b98f2dd2fe2c1640a8af9b9e6a8b8946bbf1c102271db04e81" # aaronegaas:passwordOne
KELLYEGAAS_USER_ID="basicauth:a32037e5f4cba65488401e668deabf2cf02cbf60c4271bb8d7fd731d09593d7c" # kellyegaas:passwordTwo

# Bucket Setup
http PUT https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi --auth "system:notreallyapassword"

# Group Setup
echo '{"data": {"members": ["'${AARONEGAAS_USER_ID}'", "'${KELLYEGAAS_USER_ID}'"]}}' | \
    http PUT https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/groups/egaas --auth "system:notreallyapassword"

# Collection setup
# — Circle collection
http PUT https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/circles --auth "system:notreallyapassword"

# — tasks egaas collection
echo '{"permissions":{"write": ["/buckets/TWuTPMYi/groups/egaas"]}}' | http PUT https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/tasks-egaas --auth "system:notreallyapassword"


# Record setup
# — Circle record
echo '{"data": {"name":"Egaas Family","members": ["aaronegaas", "kellyegaas"]},"permissions":{"write": ["/buckets/TWuTPMYi/groups/egaas"]}}' | \
    http POST https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/circles/records --auth "system:notreallyapassword"

# — Tasks Egaas record
echo '{"data":{"task":"milk","done":false,"circle":"egaas"}}' | \
    http POST https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/tasks-egaas/records --auth "aaronegaas:passwordOne"

# List egaas circles
http GET https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/circles/records --auth "aaronegaas:passwordOne"
http GET https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/circles/records --auth "kellyegaas:passwordTwo"

# List egaas tasks
http GET https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/tasks-egaas/records --auth "aaronegaas:passwordOne"
http GET https://kinto.dev.mozaws.net/v1/buckets/TWuTPMYi/collections/tasks-egaas/records --auth "kellyegaas:passwordTwo"
```

**Pull request closed without merging**
