### PR TITLE
Add a slack badge to the README.

### PR DESCRIPTION
**Pull request by Natim**
r? @almet

### CODE REVIEW

**Comment by Natim** [comment]
It looks like that:

readme

**Comment by n1k0** [comment]
Why did they use a serif font for that button? Mystery. 

r+

**Comment by Natim** [comment]
Oh maybe I can change that in the svg: https://kinto.dev.mozaws.net/attachments/badge.svg

**Comment by Natim** [comment]
I have updated the Verdana font (not present on my computer) with the following fallback fonts: ``DejaVu Sans,Verdana,Geneva,sans-serif``

**Comment by almet** [comment]
Cool. Just not sure about the color, but that's great :)

**Pull request merged**
