### PR TITLE
Follow Dockerflow recommendations (fixes #998)

### LINKED ISSUE #998: Check compliance with Dockerflow spec
See https://github.com/mozilla-services/Dockerflow

* `$PORT` env variable
* Copy to `/app`
* `app` group:user
* `USER` directive
* `ENTRYPOINT` directive
* ...

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #998

Apparently we can't run two commands in one `CMD` instruction when using `ENTRYPOINT`.

Because #292 was never implemented, we can't have the `kinto` command as the entrypoint and `migrate` + `start` in the `CMD`.

### CODE REVIEW

**Comment by leplatrem** [comment]
Ideally, if we could have multiple commands in `kinto` CLI, we should do:

```
ENTRYPOINT kinto
CMD migrate start --ini=$INI --port=$PORT
```

**Comment by glasserc** [comment]
I'm not crazy about the multiple-commands thing. Parsing such a command line sounds kind of crazy (`--ini` has to apply to both `migrate` and `start`, but `--port` should only apply to `start`?). Why don't we define a special command migrate-and-start for this use case? Or maybe define a [setup.py entrypoint](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/) in Python and call it `kinto-run-in-docker`?

**Comment by mostlygeek** [comment]
Multiple commands is ok. The recommended way to do this is with a `run.sh`. You could use balrog's [run.sh](https://github.com/mozilla/balrog/blob/master/scripts/run.sh) as an example. 

Your `ENTRYPOINT` will be the run.sh. You don't need a `CMD` in your dockerfile. 

What's the rational behind doing `migrate start ...` with every command? Does that modify the schema of the underlying database?

**Comment by glasserc** [comment]
Yes, `kinto migrate` updates the database schema to bring it up to date with the code that's running against it. This is especially important for the first run, which initializes the schema :)

**Comment by Natim** [comment]
> This is especially important for the first run, which initializes the schema :)

Note that if no migration are necessary this will be really fast, it will also detect error while trying to access the DB.

**Comment by mostlygeek** [comment]
Schema migration should be explicit, separated and not default. It is better to have migration and server startup as two discrete functions. Using `migrate-and-start` as a default is convenient during development but is too risky for production. 

For ops, code deployments and schema changes are usually discrete steps. Deployment are either: 

1. Update the schema, old code continues working. Deploy new code.
2. Deploy new code, continues working with old schema. Update the schema.

**Comment by leplatrem** [comment]
Thanks for your feedback on this!

I'd like to recall that the `Dockerfile` of this repo is not the one that is used by ops at Mozilla (we use [a distribution of various plugins: kinto-dist](https://github.com/mozilla-services/kinto-dist/blob/master/Dockerfile)).

I personally find it super convenient to be able to do `docker run kinto` and get an instance running. But since we use the memory backend by default, we don't need `migrate` by default.

So we can put `kinto` as the entrypoint, and let the commands be `start`, `migrate` etc. as for the CLI.
That means if someone wants to run the container with a postgres database, it will be necessary to run migrate and start as separate commands. After giving it some thoughts, it makes sense.

We'll still probably need a `run.sh` file, since we'll want to set `--ini $KINTO_INI` as a default argument for every command.

**Pull request merged**
