### PR TITLE
Fix secret in ini on Python 3 (fixes #341)

### PR DESCRIPTION
**Pull request by leplatrem**
@Natim r?

### CODE REVIEW

**Comment by Natim** [comment]
r+

**Comment by Natim** [comment]
It is hard to grasp what got fixed without a test :)

**Comment by leplatrem** [comment]
Since no test existed for that part, I felt lazy to start them :]

**Comment by Natim** [comment]
I think if we are fixing a bug there we should add one.

**Comment by leplatrem** [comment]
Will do.

**Pull request merged**
