### PR TITLE
Support old settings

### LINKED ISSUE #596: Add support for previous backend configuration values ?
```
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/initialization.py", line 534, in initialize
    config.include("kinto.core", route_prefix=api_version)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 798, in include
    c(configurator)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/__init__.py", line 151, in includeme
    step_func(config)
  File "/home/mathieu/Code/Mozilla/kinto/kinto/core/initialization.py", line 203, in setup_storage
    raise ConfigurationError("Invalid storage backend: %s" % backend)
pyramid.exceptions.ConfigurationError: Invalid storage backend: <cliquet.storage.postgresql.Storage object at 0x7fb490042690>
```

### PR DESCRIPTION
**Pull request by glasserc**
Fixes #596.

### CODE REVIEW

**Comment by Natim** [comment]
This is great thanks :+1:

**Comment by leplatrem** [comment]
Oh, but you forgot `kinto.logging_renderer` and `kinto.event_listeners` !

Not a big deal :)

**Comment by glasserc** [comment]
Do you think I should do those too, or are you merely mentioning them for completeness? `logging_renderer` could make use of the same logic, but `event_listeners` will be harder.

**Comment by leplatrem** [comment]
If you have some bandwidth you can do logging_renderer and we release a minor. For the other one it only applies to the default redis listener, which I don't think it's is massively used... No need to spend energy on this!

**Pull request merged**
