### PR TITLE
Clean-up unused globalSettings in admin plugin

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by Natim** [comment]
Is this because the new kinto-admin is able to read the capabilities to detect the activated authentication mecanisms?

**Comment by leplatrem** [comment]
> Is this because the new kinto-admin is able to read the capabilities to detect the activated authentication mecanisms?

Yes!

**Comment by Natim** [comment]
Will it automatically select the current server with this changes?

**Comment by leplatrem** [comment]
> Will it automatically select the current server with this changes?

Yes, it's done in `index.js`

**Pull request merged**
