### PR TITLE
Kinto-issue1780:Remove assertEquals usage

### PR DESCRIPTION
**Pull request by abk-code**
Fixes # issue 1780

- [x] Add documentation.
- [ ] Add tests.
- [x] Add a changelog entry.
- [x] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)
- [ ] If you added a new configuration setting, update the [`kinto.tpl`](https://github.com/Kinto/kinto/blob/master/kinto/config/kinto.tpl) file with it.

### CODE REVIEW

**Comment by abk-code** [comment]
Few questions: 
1. I see assertEquals being used in many other files. Is the goal here to remove all the usage
or only in test_utils.py ? 
 2. I picked backend as postgresql and cache as memory while testing. Is that  right?
Thanks.

**Comment by abk-code** [comment]
@leplatrem : How do I add reviewers here? I can't seem to assign the names.

**Comment by leplatrem** [comment]
Great thanks!

The idea is to get rid of all the deprecation warnings, so replace it everywhere.

Also, could you please add a line in the CHANGELOG file please?

If you run `tox -e flake8` it should show no error (cf. https://travis-ci.org/Kinto/kinto/jobs/434615685)

**Comment by abk-code** [comment]
Thanks much. I've made the modifications requested. Please review.

**Comment by abk-code** [comment]
`tox -e flake8
GLOB sdist-make: /home/abk/kinto/setup.py
flake8 inst-nodeps: /home/abk/kinto/.tox/dist/kinto-10.1.2.dev0.zip
flake8 installed: appdirs==1.4.3,bcrypt==3.1.4,certifi==2018.8.24,cffi==1.11.5,chardet==3.0.4,colander==1.5.1,colorama==0.3.9,cornice==3.4.0,cornice-swagger==0.7.0,dockerflow==2018.4.0,flake8==3.5.0,hupper==1.3,idna==2.7,iso8601==0.1.12,jsonpatch==1.23,jsonpointer==2.0,jsonschema==2.6.0,kinto==10.1.2.dev0,logging-color-formatter==1.0.2,mccabe==0.6.1,packaging==18.0,PasteDeploy==1.5.2,pkg-resources==0.0.0,plaster==1.0,plaster-pastedeploy==0.6,pycodestyle==2.3.1,pycparser==2.19,pyflakes==1.6.0,pyparsing==2.2.1,pyramid==1.9.2,pyramid-multiauth==0.9.0,pyramid-tm==2.2,python-dateutil==2.7.3,repoze.lru==0.7,requests==2.19.1,simplejson==3.16.0,six==1.11.0,transaction==2.2.1,translationstring==1.3,ujson==1.35,urllib3==1.23,venusian==1.1.0,waitress==1.1.0,WebOb==1.8.2,zope.deprecation==4.3.0,zope.interface==4.5.0
flake8 runtests: PYTHONHASHSEED='563059735'
flake8 runtests: commands[0] | flake8 kinto tests docs/conf.py
______________________________________ summary ______________________________________
  flake8: commands succeeded
  congratulations :)
`

**Comment by abk-code** [comment]
Can someone please review?

**Comment by leplatrem** [comment]
Great thanks! I'v just checked the test output on Travis, and those deprecations are gone ;)

**Pull request merged**
