### PR TITLE
Tutorial how to write a plugin

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by Natim** [comment]
Great :)

**Comment by almet** [comment]
Adding some more info in the text.

**Comment by almet** [comment]
updated.

**Comment by leplatrem** [comment]
Thanks.

By the way, don't take it yet, I didn't even tested it!

**Comment by leplatrem** [comment]
Ok, I went through the whole thing and could make it work :)

Now ready to review/merge!

**Comment by Natim** [comment]
I am wondering if we should not also put the code of the working plugins on github somewhere. (kinto/kinto-elasticsearch)

**Pull request merged**
