### PR TITLE
Preparing release 4.0.0

### PR DESCRIPTION
**Pull request by Natim**
**Step 1**

* [x] Update changelog
* [x] Update version in docs/conf.py
* [x] Version dependencies
* [x] If the protocol was updated, upgrade API protocol in `docs/api/index.rst` and mention the new protocol version in `CHANGELOG.rst`
* [x] Update release date in `docs/api/index.rst`

**Step 2**

* [ ] Tag vX.Y.Z
* [ ] Publish on Pypi

**Step 3**
* [x] Close milestone in Github
* [x] Create next milestone in Github
* [ ] Add entry in Github release page
* [ ] Configure the version in ReadTheDocs
* [ ] Check that a Docker image was built
* [ ] Send mail to ML
* [ ] Tweet!

- [ ] Deploy new version on demo server
- [ ] Upgrade dependency in ``kinto-dist`` repo
- [ ] Upgrade version targetted in ``kinto-heroku`` repo
- [ ] Upgrade version of Kinto server for the tests of clients and plugins repos
  (*kinto-http.js, kinto-http.py, kinto-attachment, etc.*)

@leplatrem r?

### CODE REVIEW

**Comment by leplatrem** [comment]
\o/ 

I was wondering: don't we have to provide a `version.json` file before uploading to pypi? shouldn't we add a note about this in the *releasing* docs/PR tasks?

**Comment by Natim** [comment]
> don't we have to provide a version.json file before uploading to pypi? 
We probably should yes.

**Comment by leplatrem** [comment]
nits:

* ` Fix Redis get_accessible_object implementation (#725)` → Remove?
* typo: ``kinto.core`` resources are **now** schemaless

**Comment by leplatrem** [comment]
r+

**Pull request merged**
