### PR TITLE
Fix Travis CI build for Python 3.5

### LINKED ISSUE #411: Interpreter not found for Python 3.5 on TravisCI
capture d ecran de 2016-01-29 21-48-19

### PR DESCRIPTION
**Pull request by cbjadwani**
Fixes #411

### CODE REVIEW

**Comment by leplatrem** [comment]
Thanks for your contribution!

I checked Travis and it worked well.

I just wonder if we should do the same for py27, py34 and pypy now :) What do you think ?

**Comment by almet** [comment]
Yes, it seems that matrix is the way to go for a better travis integration.

**Comment by cbjadwani** [comment]
Matrix is not required for other python versions.  This fix was needed for 3.5 to workaround [travis-ci/travis-build#4794](https://github.com/travis-ci/travis-ci/issues/4794)

**Comment by leplatrem** [comment]
I agree to merge it like this. Let's iterate if we can do better!

Thanks again!

**Pull request merged**
