### PR TITLE
Remove unsolicited log.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by leplatrem** [comment]
What does it mean? Can you elaborate please?

**Comment by Natim** [comment]
It seems that we log really often this. For some reason it appears as an error log in our development environment even if it looks like a info log here.

It looks like a left over from the past, I would gladly remove it.

**Comment by leplatrem** [comment]
> It seems that we log really often this. For some reason it appears as an error log in our development 

Do you have custom config / formatter?

This is supposed to log the batch subrequests. I would keep it, add a setting maybe?

**Comment by leplatrem** [comment]
```
kinto init --ini=/tmp/conf.ini
kinto start --ini=/tmp/conf.ini
```
The logs make sense if I do that: 
```
echo '{"requests":[{"path":"/accounts"}]}' | http POST :8888/v1/batch
```
Look:
Screenshot from 2019-10-22 17-44-00

**Pull request closed without merging**
